[workspace]
members = [
    "node",
    "pallets/template",
    "pallets/template2",
     "runtime",
    "pallets/StorageConsumer",
    "pallets/StorageProvider",
    "pallets/useStorage",
    "pallets/ocw"
]
[profile.release]
panic = "unwind"
